export const APP_IS_LOADING = 'APP_IS_LOADING';

export const AUTHENTICATE_FAIL = 'AUTHENTICATE_FAIL';
export const AUTHENTICATE_SYNC = 'AUTHENTICATE_SYNC';

export const CREATE_TRIP_FAIL = 'CREATE_TRIP_FAIL';
export const CREATE_TRIP_SYNC = 'CREATE_TRIP_SYNC';

export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

export const DELETE_TRIP_FAIL = 'DELETE_TRIP_FAIL';
export const DELETE_TRIP_SYNC = 'DELETE_TRIP_SYNC';

export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const REMOVE_USER_FROM_TRIP_FAIL = 'REMOVE_USER_FROM_TRIP_FAIL';
export const REMOVE_USER_FROM_TRIP_SYNC = 'REMOVE_USER_FROM_TRIP_SYNC';

export const STORE_USER_FAIL = 'STORE_USER_FAIL';
export const STORE_USER_SYNC = 'STORE_USER_SYNC';

export const UPDATE_TRIP_FAIL = 'UPDATE_TRIP_FAIL';
export const UPDATE_TRIP_SYNC = 'UPDATE_TRIP_SYNC';

export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const UPDATE_USER_SYNC = 'UPDATE_USER_SYNC';
